### ISSUE TITLE
Create the "Personal Details -Mentee" route that will allow users to add their personal details

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/mentorlst-frontend#10]
## Description
A mentee should be able to add their personal details to a form on the page

## Scenarios

- A user can add their full names.
- A user can add a gender.
- A user can add their Date of Birth
- A user can add their Linkedin profile
- A user can add their phone number
- A user can add their country
- A user can add their timezone

## Tasks

-  [x] Create a form for the user to fill out
 - [x] There should be a submit button on the page that allows the user to submit their information 
 - [x] Provide a route for the mentee's details
 - [x] There should be a submit button on the page that allows the user to submit their information
