### ISSUE TITLE
Write the mentee flow logic to allow a mentee to signup for an account

### ISSUE THREAD

**Issue by McbullIan** [SpaceyaTech/mentorlst-frontend#24]
## Description
A user needs to provide all the necessary information before submitting the form to the backend

## Scenarios

- A user needs to X provide their email address.
- A user needs to provide a password.
- A user needs to provide their full name, date of birth, phone number, and nationality
- A user needs to provide their job title, level of experience, LinkedIn profile, and field of interest

## Tasks

-  [ ]  Create a user object that has all the necessary information
-  [x] Write form validation logic to only allow a user to navigate to a different route after providing all the required input fields
 - [x] Only submit when the user has provided all the necessary information
